# Generated by Django 5.1.3 on 2024-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admingreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineid', models.CharField(max_length=100)),
                ('adname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MachineBsfl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addbsfl', models.IntegerField(default=0)),
                ('bsfl', models.IntegerField()),
                ('machineid', models.CharField(max_length=50)),
                ('bsreceived', models.CharField(blank=True, max_length=50, null=True)),
                ('composting', models.CharField(blank=True, max_length=50, null=True)),
                ('manure', models.CharField(blank=True, max_length=50, null=True)),
                ('com', models.IntegerField()),
                ('man', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MachinePyro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addpyro', models.IntegerField(default=0)),
                ('pyro', models.IntegerField()),
                ('machineid', models.CharField(max_length=50)),
                ('received', models.CharField(blank=True, max_length=50, null=True)),
                ('processing', models.CharField(blank=True, max_length=50, null=True)),
                ('dispatched', models.CharField(blank=True, max_length=50, null=True)),
                ('pro', models.IntegerField()),
                ('con', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usergreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineid', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
