# Generated by Django 5.1.3 on 2024-12-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergreen',
            name='Bsmachineid',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergreen',
            name='bsflweight',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergreen',
            name='pyroweigh',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
