# Generated by Django 5.1.3 on 2024-12-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usergreen_addpyroweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergreen',
            name='addbsflweight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergreen',
            name='carbon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
